version: '3.1'

services:
   backend:
   
    image: py
    #build: ./flask-app/Dockerfile
      # working_dir: /app/flask-app
    container_name: backend
    restart: always

    ports:
     - 5000:5000
    depends_on:
     - es
    networks:
      - frontend

   nginx: 
    image: ngx
    container_name: production_nginx
    networks:
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
   
   es:

    image: "elasticsearch:5"
    networks:
      - frontend
    restart: always
    volumes:
      - ./ES_DATA:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"

networks:
  frontend:



       